### ISSUE TITLE
Remove depedency on VideoInput layer

### ISSUE THREAD

**Issue by moaljazaery** [facebookresearch/VMZ#47]
I am trying to build live demo taking on fly sample to classify. How can I remove the dependency on  the VideoInput layer?

**Comment by dutran** [comment]
@moaljazaery if you have some video loader written in python, and perform the transformations (re-scale, crop, normalize etc. as done in VideoInputOp), then we can do inference completely in caffe2 (python land). But I suggest to be very careful to have the same set of transformation (color channel order, etc) so that you can have the best accuracy.
