### ISSUE TITLE
Feature Extraction for videos in real time

### ISSUE THREAD

**Issue by nerdykamil** [facebookresearch/VMZ#59]
Hey, thank you for the great work. I was able to extract features through feature extraction script and train model using those features. I was wondering how can I tweak this script to get features of video in real time, as what could be the list file in that case.

**Comment by dutran** [comment]
Currently that script uses VideoInputOp that need to run by mini-batch. Alternatively, you can write a simple video loader (using python opencv or something similar python ffmpeg) to read video from file or live webcam/camera, then preprocess (scale, crop, normalize), then feed them to the workflow for inference only. I wish I can do this when I have time. So this is in my wish list, since it will make a good live demo. cc: @HengCV @CHJoanna

**Comment by keunhong** [comment]
Could you clarify how the inputs are normalized during training? Are the inputs between -1 and +1?
