### ISSUE TITLE
frame rate for instagram models

### ISSUE THREAD

**Issue by albanie** [facebookresearch/VMZ#95]
Thanks for sharing the pretrained models! 
What was the frame rate used by the instgram models during pretraining? 
Apologies if it's written somewhere, I couldn't find it in the paper.

**Comment by bjuncek** [comment]
@albanie can you point me to the exact model?
I haven't trained them but I can check the log files :)

**Comment by bjuncek** [comment]
also, as a sidenote, your website was the most entertaining read since the [US military report on the effect on atomic bomb on brewed alcoholic beverages](https://www.npr.org/sections/krulwich/2012/09/18/161338723/u-s-explodes-atomic-bombs-near-beers-to-see-if-they-are-safe-to-drink?t=1570703647207)

**Comment by bjuncek** [comment]
Hi @albanie, so "the IG data is encoded at many different frame rates. The peaks are at 24 and 30, but the fps distribution was spread out quite a bit".

**Comment by albanie** [comment]
OK, great - in that case I guess the models should be fairly robust to whatever I run it with. Thanks for your help!
